name: Java CI/CD

on:
  push:
    branches: [master]

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Maven Verify
        run: mvn clean verify
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: unit-test.dockerfile
          context: .
          push: true
          tags: hafidzencis/capstone-coverage:latest

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hafidzencis/capstone:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./dev.env"
          target: "/home/${{ secrets.SSH_USER }}"
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop capstone capstone-coverage
            docker rmi hafidzencis/capstone:latest hafidzencis/capstone-coverage:latest  
            docker pull hafidzencis/capstone:latest
            docker pull hafidzencis/capstone-coverage:latest
            docker run -d --rm --name capstone-coverage -p 8000:80 hafidzencis/capstone-coverage:latest
            docker run -d --rm --name capstone -p 80:8080 --env-file=dev.env --network mynetwork -v "/home/ec2-user/images":/app/images hafidzencis/capstone:latest
